### ISSUE TITLE
AssertionError with nvim-qt

### ISSUE THREAD

**Issue by Mte90** [ms-jpq/pynvim_pp#6]
So I have the latest nvim version and the latest nvim-qt.

I get this error continuously in the UI:

![image](https://github.com/ms-jpq/pynvim_pp/assets/403283/160e016e-b9bd-45f7-8553-55c6c314102b)
![image](https://github.com/ms-jpq/pynvim_pp/assets/403283/e3f70efc-0512-4aa2-b354-be05d725c7e5)

As I can see that is reporting all commands from nvim-qt

**Comment by ms-jpq** [comment]
i fixed it on coq's side, was just a diagnostic for telling me about an unknown event, but it doesn't hurt to disable

**Comment by ms-jpq** [comment]
thanks for letting me know :)
